### ISSUE TITLE
Device.tablet not working in simulator

### ISSUE THREAD

**Issue by mrphilipandrews** [argyleink/Mobile-Detection#3]
Device.tablet comes back as 'undefined' in iOS simulator iOS8/iPad 2

**Comment by argyleink** [comment]
Need more details, my test came back `True`

![screen shot 2015-02-18 at 6 19 10 pm](https://cloud.githubusercontent.com/assets/1134620/6260895/c0a69c64-b79a-11e4-95d4-8b279a302e75.png)
